---
- name: Install Apache2 on web server
  hosts: slave1  # Update with your target host group for Apache
  become: yes
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes

- name: Install Nginx on web server
  hosts: slave2  # Update with your target host group for Nginx
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
